// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(NumberParserDbContext))]
    partial class NumberParserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Data.Entities.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileTypeFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileTypeFormat = "TEXT"
                        },
                        new
                        {
                            Id = 2,
                            FileTypeFormat = "XML"
                        },
                        new
                        {
                            Id = 3,
                            FileTypeFormat = "JSON"
                        });
                });

            modelBuilder.Entity("DAL.Data.Entities.InputOutputResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileTypeId")
                        .HasColumnType("int");

                    b.Property<string>("InputList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InputTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutputList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OutputTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("InputOutputResult");
                });

            modelBuilder.Entity("DAL.Data.Entities.InputOutputResult", b =>
                {
                    b.HasOne("DAL.Data.Entities.FileType", "FileType")
                        .WithMany("InputOutputResults")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("DAL.Data.Entities.FileType", b =>
                {
                    b.Navigation("InputOutputResults");
                });
#pragma warning restore 612, 618
        }
    }
}
